.ORIG x3000

AND R1, R1, #0
AND R2, R2, #0
LD R1, TOP_BORDER    ;ascii code for 0
LD R2, BOTTOM_BORDER ;ascii code for 9

TRAP x23

ADD R1, R0, R1
BRn DONE

ADD R2, R0, R2
BRp DONE

  SUITABLE LD R0, SUITABLE_WARNING
  DONE TRAP x21

TOP_BORDER .FILL xFFD0
BOTTOM_BORDER .FILL xFFC7
SUITABLE_WARNING .FILL x21 ;It's ascii number

HALT
.END